from .settings import XBB, TPLUS, SYNC_INTERVAL_SEC, TOKEN_REFRESH_DAYS, MAX_RETRY, REQUEST_TIMEOUT, XBB_PAGE_SIZE, AUTO_DELETE_CODES
from .field_maps import XBB_TO_TPLUS_PARTNER_TYPE, TPLUS_TO_XBB_PARTNER_TYPE
